bot:
  token: "YOUR_TOKEN_HERE"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "svarme"
admin:
  email: "admin@admin.com"
  password: "123456789"

gigachat:
  token: "YOUR_GIGACHAT_TOKEN"

redis:
  host: "localhost"
  port: 6379
  password: 12345
  db: 0

rabbit:
  host: "localhost"
  port: 5672
  user: guest
  password: guest
