"""message tables

Revision ID: 4da5da7809d2
Revises: 24e2dc9bcfed
Create Date: 2026-03-19 21:53:59.949850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da5da7809d2'
down_revision: Union[str, None] = '24e2dc9bcfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_board_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_cbm_game_user')
    )
    op.create_table('temp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_messages_game_user', 'temp_messages', ['game_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_messages_game_user', table_name='temp_messages')
    op.drop_table('temp_messages')
    op.drop_table('category_board_messages')
    # ### end Alembic commands ###
