"""relationship with lobby message

Revision ID: 556786f2d6b1
Revises: 91144b1a7ba8
Create Date: 2026-03-16 21:01:57.624106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556786f2d6b1'
down_revision: Union[str, None] = '91144b1a7ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'current_highest_bet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('current_highest_bet', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
