"""Added username and first_name

Revision ID: 27ec6c0b9833
Revises: add_chat_id_to_game
Create Date: 2026-03-11 21:07:12.110445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ec6c0b9833'
down_revision: Union[str, None] = 'add_chat_id_to_game'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
