"""Refactor models to Mapped style

Revision ID: 32dc53ea9fba
Revises: 3bcec2bf915d
Create Date: 2026-03-08 21:30:51.717156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32dc53ea9fba'
down_revision: Union[str, None] = '3bcec2bf915d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'round',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('game', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_final_bets', 'is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('statistic', 'games_played',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistic', 'max_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistic', 'right_answers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistic', 'wins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'game_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'game_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('statistic', 'wins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistic', 'right_answers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistic', 'max_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistic', 'games_played',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_final_bets', 'is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('game', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('game', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category', 'round',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
