"""GamePlayerModel logic

Revision ID: 19257ac69691
Revises: 556786f2d6b1
Create Date: 2026-03-17 09:58:10.778557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19257ac69691'
down_revision: Union[str, None] = '556786f2d6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_game_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'points')
    op.drop_column('user', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_game_id_fkey', 'user', 'game', ['game_id'], ['id'], ondelete='SET NULL')
    op.drop_table('game_players')
    # ### end Alembic commands ###
