"""game mode for matchmaking

Revision ID: 24e2dc9bcfed
Revises: 2386851c10ea
Create Date: 2026-03-19 18:06:55.935770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e2dc9bcfed'
down_revision: Union[str, None] = '2386851c10ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchmaking', sa.Column('game_mode', sa.String(length=50), nullable=True))
    op.execute("UPDATE matchmaking SET game_mode = 'standard'")
    op.alter_column('matchmaking', 'game_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchmaking', 'game_mode')
    # ### end Alembic commands ###
