"""search message field

Revision ID: 84328841750a
Revises: 4da5da7809d2
Create Date: 2026-03-19 22:30:17.458637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84328841750a'
down_revision: Union[str, None] = '4da5da7809d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchmaking', sa.Column('search_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchmaking', 'search_message_id')
    # ### end Alembic commands ###
