"""initial

Revision ID: 3bcec2bf915d
Revises: 
Create Date: 2026-03-07 18:06:18.089592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcec2bf915d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_mode', sa.String(length=50), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('choosing_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('active_question_id', sa.Integer(), nullable=True),
    sa.Column('question_asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('current_highest_bet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('game_answered_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_final_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('right_answers', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('game_final_bets')
    op.drop_table('game_answered_questions')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('game_categories')
    op.drop_table('game')
    op.drop_table('category')
    # ### end Alembic commands ###
